import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import NextAuthPovider from '../provider/NextAuthPovider';
import UseQueryProvider from '../provider/UseQueryProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
   <NextAuthPovider>
    <UseQueryProvider>
     <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    
      <body className="min-h-full  w-full relative  flex  flex-col justify-center mx-auto  ">
       <Navbar/>
         <div className='min-h-screen w-full mx-auto overflow-hidden'>
           {children}
         </div>
          <Footer/>
   
      </body>
    </html>
    </UseQueryProvider>
   </NextAuthPovider>
   </>
  );
}
