import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar/Navbar";
import NextAuthPovider from "./provider/NextAuthPovider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
   <NextAuthPovider>
     <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    
      <body className="min-h-full  flex  flex-col  mx-auto  ">
       <Navbar/>
          {children}
   
      </body>
    </html>
   </NextAuthPovider>
   </>
  );
}
